INSERT INTO characters (id, name, colloquial_name, type, lore, image_path)
VALUES (1, 'The Artist', NULL, 'Killer', '', 'the_artist.webp'),
       (2, 'The Demogorgan', NULL, 'Killer', '', 'the_demogorgan.webp'),
       (3, 'The Hillbilly', NULL, 'Killer', '', 'the_hillbilly.webp'),
       (4, 'The Nightmare', NULL, 'Killer', '', 'the_nightmare.webp'),
       (5, 'The Singularity', NULL, 'Killer', '', 'the_singularity.webp'),
       (6, 'The Wraith', NULL, 'Killer', '', 'the_wraith.webp'),
       (7, 'The Blight', NULL, 'Killer', '', 'the_blight.webp'),
       (8, 'The Doctor', NULL, 'Killer', '', 'the_doctor.webp'),
       (9, 'The Huntress', NULL, 'Killer', '', 'the_huntress.webp'),
       (10, 'The Nurse', NULL, 'Killer', '', 'the_nurse.webp'),
       (11, 'The Skull Merchant', NULL, 'Killer', '', 'the_skull_merchant.webp'),
       (12, 'The Xenomorph', NULL, 'Killer', '', 'the_xenomorph.webp'),
       (13, 'The Cannibal', NULL, 'Killer', '', 'the_cannibal.webp'),
       (14, 'The Dredge', NULL, 'Killer', '', 'the_dredge.webp'),
       (15, 'The Knight', NULL, 'Killer', '', 'the_knight.webp'),
       (16, 'The Oni', NULL, 'Killer', '', 'the_oni.webp'),
       (17, 'The Spirit', NULL, 'Killer', '', 'the_spirit.webp'),
       (18, 'The Cenobite', NULL, 'Killer', '', 'the_cenobite.webp'),
       (19, 'The Executioner', NULL, 'Killer', '', 'the_executioner.webp'),
       (20, 'The Legion', NULL, 'Killer', '', 'the_legion.webp'),
       (21, 'The Onyro', NULL, 'Killer', '', 'the_onyro.webp'),
       (22, 'The Trapper', NULL, 'Killer', '', 'the_trapper.webp'),
       (23, 'The Clown', NULL, 'Killer', '', 'the_clown.webp'),
       (24, 'The Ghost Face', NULL, 'Killer', '', 'the_ghost_face.webp'),
       (25, 'The Lich', NULL, 'Killer', '', 'the_lich.webp'),
       (26, 'The Pig', NULL, 'Killer', '', 'the_pig.webp'),
       (27, 'The Trickster', NULL, 'Killer', '', 'the_trickster.webp'),
       (28, 'The Dark Lord', NULL, 'Killer', '', 'the_dark_lord.webp'),
       (29, 'The Good Guy', NULL, 'Killer', '', 'the_good_guy.webp'),
       (30, 'The Mastermind', NULL, 'Killer', '', 'the_mastermind.webp'),
       (31, 'The Plague', NULL, 'Killer', '', 'the_plague.webp'),
       (32, 'The Twins', NULL, 'Killer', '', 'the_twins.webp'),
       (33, 'The Deathslinger', NULL, 'Killer', '', 'the_deathslinger.webp'),
       (34, 'The Hag', NULL, 'Killer', '', 'the_hag.webp'),
       (35, 'The Nemesis', NULL, 'Killer', '', 'the_nemesis.webp'),
       (36, 'The Shape', NULL, 'Killer', '', 'the_shape.webp'),
       (37, 'The Unknown', NULL, 'Killer', '', 'the_unknown.webp'),
       (38, 'Ace Visconti', NULL, 'Survivor', '', 'ace_visconti.jpg'),
       (39, 'Elodie Rakoto', NULL, 'Survivor', '', 'elodie_rakoto.jpg'),
       (40, 'Lara Croft', NULL, 'Survivor', '', 'lara_croft.jpg'),
       (41, 'Sable Ward', NULL, 'Survivor', '', 'sable_ward.webp'),
       (42, 'Ada Wong', NULL, 'Survivor', '', 'ada_wong.jpg'),
       (43, 'Felix Richter', NULL, 'Survivor', '', 'felix_richter.jpg'),
       (44, 'Laurie Strode', NULL, 'Survivor', '', 'laurie_strode.jpg'),
       (45, 'Steve Harrington', NULL, 'Survivor', '', 'steve_harrington.jpg'),
       (46, 'Adam Francis', NULL, 'Survivor', '', 'adam_francis.jpg'),
       (47, 'Feng Min', NULL, 'Survivor', '', 'feng_min.jpg'),
       (48, 'Leon Scott Kennedy', NULL, 'Survivor', '', 'leon_scott_kennedy.jpg'),
       (49, 'Thalita Lyra', NULL, 'Survivor', '', 'thalita_lyra.jpg'),
       (50, 'Alan Wake', NULL, 'Survivor', '', 'alan_wake.webp'),
       (51, 'Gabriel Soma', NULL, 'Survivor', '', 'gabriel_soma.jpg'),
       (52, 'Meg Thomas', NULL, 'Survivor', '', 'meg_thomas.jpg'),
       (53, 'The Troupe', NULL, 'Survivor', '', 'the_troupe.webp'),
       (54, 'Ash Williams', NULL, 'Survivor', '', 'ash_williams.jpg'),
       (55, 'Haddie Kaur', NULL, 'Survivor', '', 'haddie_kaur.jpg'),
       (56, 'Mikaela Reid', NULL, 'Survivor', '', 'mikaela_reid.jpg'),
       (57, 'Trevor Belmont', NULL, 'Survivor', '', 'trevor_belmont.webp'),
       (58, 'Cheryl Mason', NULL, 'Survivor', '', 'cheryl_mason.jpg'),
       (59, 'Jake Park', NULL, 'Survivor', '', 'jake_park.jpg'),
       (60, 'Nancy Wheeler', NULL, 'Survivor', '', 'nancy_wheeler.jpg'),
       (61, 'Vittorio Toscano', NULL, 'Survivor', '', 'vittorio_toscano.jpg'),
       (62, 'Claudette Morel', NULL, 'Survivor', '', 'claudette_morel.jpg'),
       (63, 'Jane Romero', NULL, 'Survivor', '', 'jane_romero.jpg'),
       (64, 'Nea Karlsson', NULL, 'Survivor', '', 'nea_karlsson.jpg'),
       (65, 'William Bill Overbeck', NULL, 'Survivor', '', 'william_bill_overbeck.jpg'),
       (66, 'David King', NULL, 'Survivor', '', 'david_king.jpg'),
       (67, 'Jeff Johansen', NULL, 'Survivor', '', 'jeff_johansen.jpg'),
       (68, 'Nicolas Cage', NULL, 'Survivor', '', 'nicolas_cage.jpg'),
       (69, 'Yoichi Asakawa', NULL, 'Survivor', '', 'yoichi_asakawa.jpg'),
       (70, 'David Tapp', NULL, 'Survivor', '', 'david_tapp.jpg'),
       (71, 'Jill Valentine', NULL, 'Survivor', '', 'jill_valentine.jpg'),
       (72, 'Quentin Smith', NULL, 'Survivor', '', 'quentin_smith.jpg'),
       (73, 'Yui Kimura', NULL, 'Survivor', '', 'yui_kimura.jpg'),
       (74, 'Dwight Fairfield', NULL, 'Survivor', '', 'dwight_fairfield.jpg'),
       (75, 'Jonah Vasquez', NULL, 'Survivor', '', 'jonah_vasquez.jpg'),
       (76, 'Rebecca Chambers', NULL, 'Survivor', '', 'rebecca_chambers.jpg'),
       (77, 'Yun Jin Lee', NULL, 'Survivor', '', 'yun_jin_lee.jpg'),
       (78, 'Ellen Ripley', NULL, 'Survivor', '', 'ellen_ripley.jpg'),
       (79, 'Kate Denson', NULL, 'Survivor', '', 'kate_denson.jpg'),
       (80, 'Renato Lyra', NULL, 'Survivor', '', 'renato_lyra.jpg'),
       (81, 'Zarina Kassir', NULL, 'Survivor', '', 'zarina_kassir.jpg');
