INSERT INTO perks (character_id, name, colloquial_name, description, type, image_path)
VALUES (10, 'A Nurses Calling', '', '', 'Killer', 'a_nurses_calling.webp'),
       (4, 'Face The Darkness', '', '', 'Killer', 'face_the_darkness.webp'),
       (48, 'Potential Energy', '', '', 'Survivor', 'potential_energy.webp'),
       (38, 'Ace In The Hole', '', '', 'Survivor', 'ace_in_the_hole.webp'),
       (46, 'Fast Track', '', '', 'Survivor', 'fast_track.webp'),
       (46, 'Power Struggle', '', '', 'Survivor', 'power_struggle.webp'),
       (46, 'Adrenaline', '', '', 'Survivor', 'adrenaline.webp'),
       (46, 'Finesse', '', '', 'Survivor', 'finesse.webp'),
       (6, 'Predator', '', '', 'Killer', 'predator.webp'),
       (46, 'Aftercare', '', '', 'Survivor', 'aftercare.webp'),
       (7, 'Fire Up', '', '', 'Killer', 'fire_up.webp'),
       (48, 'Premonition', '', '', 'Survivor', 'premonition.webp'),
       (13, 'Agitation', '', '', 'Killer', 'agitation.webp'),
       (47, 'Fixated', '', '', 'Survivor', 'fixated.webp'),
       (47, 'Prove Thyself', '', '', 'Survivor', 'prove_thyself.webp'),
       (47, 'Alert', '', '', 'Survivor', 'alert.webp'),
       (47, 'Flashbang', '', '', 'Survivor', 'flashbang.webp'),
       (47, 'Quick And Quiet', '', '', 'Survivor', 'quick_and_quiet.webp'),
       (11, 'Alien Instinct', '', '', 'Killer', 'alien_instinct.webp'),
       (47, 'Flip Flop', '', '', 'Survivor', 'flip_flop.webp'),
       (47, 'Quick Gambit', '', '', 'Survivor', 'quick_gambit.webp'),
       (47, 'Any Means Necessary', '', '', 'Survivor', 'any_means_necessary.webp'),
       (13, 'Floods Of Rage', '', '', 'Killer', 'floods_of_rage.webp'),
       (5, 'Rancor', '', '', 'Killer', 'rancor.webp'),
       (47, 'Appraisal', '', '', 'Survivor', 'appraisal.webp'),
       (50, 'Fogwise', '', '', 'Survivor', 'fogwise.webp'),
       (13, 'Rapid Brutality', '', '', 'Killer', 'rapid_brutality.webp'),
       (48, 'Autodidact', '', '', 'Survivor', 'autodidact.webp'),
       (48, 'For The People', '', '', 'Survivor', 'for_the_people.webp'),
       (48, 'Reactive Healing', '', '', 'Survivor', 'reactive_healing.webp'),
       (11, 'Awakened Awareness', '', '', 'Killer', 'awakened_awareness.webp'),
       (5, 'Forced Hesitation', '', '', 'Killer', 'forced_hesitation.webp'),
       (48, 'Reassurance', '', '', 'Survivor', 'reassurance.webp'),
       (48, 'Babysitter', '', '', 'Survivor', 'babysitter.webp'),
       (5, 'Forced Penance', '', '', 'Killer', 'forced_penance.webp'),
       (48, 'Red Herring', '', '', 'Survivor', 'red_herring.webp'),
       (48, 'Background Player', '', '', 'Survivor', 'background_player.webp'),
       (18, 'Franklins Demise', '', '', 'Killer', 'franklins_demise.webp'),
       (48, 'Remember Me', '', '', 'Killer', 'remember_me.webp'),
       (47, 'Balanced Landing', '', '', 'Survivor', 'balanced_landing.webp'),
       (48, 'Friendly Competition', '', '', 'Survivor', 'friendly_competition.webp'),
       (48, 'Repressed Alliance', '', '', 'Survivor', 'repressed_alliance.webp'),
       (6, 'Bamboozle', '', '', 'Killer', 'bamboozle.webp'),
       (5, 'Friends Till The End', '', '', 'Killer', 'friends_till_the_end.webp'),
       (48, 'Residual Manifest', '', '', 'Survivor', 'residual_manifest.webp'),
       (11, 'Batteries Included', '', '', 'Killer', 'batteries_included.webp'),
       (5, 'Furtive Chase', '', '', 'Killer', 'furtive_chase.webp'),
       (48, 'Resilience', '', '', 'Survivor', 'resilience.webp'),
       (18, 'Bbq And Chili', '', '', 'Killer', 'bbq_and_chili.webp'),
       (11, 'Game Afoot', '', '', 'Killer', 'game_afoot.webp'),
       (48, 'Resurgence', '', '', 'Survivor', 'resurgence.webp'),
       (6, 'Beast Of Prey', '', '', 'Killer', 'beast_of_prey.webp'),
       (5, 'Gearhead', '', '', 'Killer', 'gearhead.webp'),
       (5, 'Retribution', '', '', 'Killer', 'retribution.webp'),
       (48, 'Better Than New', '', '', 'Survivor', 'better_than_new.webp'),
       (11, 'Genetic Limits', '', '', 'Killer', 'genetic_limits.webp'),
       (48, 'Rookie Spirit', '', '', 'Survivor', 'rookie_spirit.webp'),
       (47, 'Better Together', '', '', 'Survivor', 'better_together.webp'),
       (11, 'Gift Of Pain', '', '', 'Killer', 'gift_of_pain.webp'),
       (5, 'Ruin', '', '', 'Killer', 'ruin.webp'),
       (47, 'Bite The Bullet', '', '', 'Survivor', 'bite_the_bullet.webp'),
       (11, 'Grim Embrace', '', '', 'Killer', 'grim_embrace.webp'),
       (48, 'Saboteur', '', '', 'Survivor', 'saboteur.webp'),
       (5, 'Bitter Murmur', '', '', 'Killer', 'bitter_murmur.webp'),
       (13, 'Hangmans Trick', '', '', 'Killer', 'hangmans_trick.webp'),
       (5, 'Save The Best For Last', '', '', 'Killer', 'save_the_best_for_last.webp'),
       (48, 'Blast Mine', '', '', 'Survivor', 'blast_mine.webp'),
       (48, 'Hardened', '', '', 'Survivor', 'hardened.webp'),
       (48, 'Scavenger', '', '', 'Survivor', 'scavenger.webp'),
       (5, 'Blood Echo', '', '', 'Killer', 'blood_echo.webp'),
       (5, 'Haunted Ground', '', '', 'Killer', 'haunted_ground.webp'),
       (48, 'Scene Partner', '', '', 'Survivor', 'scene_partner.webp'),
       (5, 'Blood Favor', '', '', 'Killer', 'blood_favor.webp'),
       (48, 'Head On', '', '', 'Survivor', 'head_on.webp'),
       (48, 'Second Wind', '', '', 'Survivor', 'second_wind.webp'),
       (48, 'Blood Pact', '', '', 'Survivor', 'blood_pact.webp'),
       (5, 'Hoarder', '', '', 'Killer', 'hoarder.webp'),
       (48, 'Self Aware', '', '', 'Survivor', 'self_aware.webp'),
       (48, 'Blood Rush', '', '', 'Survivor', 'blood_rush.webp'),
       (48, 'Hope', '', '', 'Survivor', 'hope.webp'),
       (48, 'Self-Care', '', '', 'Survivor', 'self_care.webp'),
       (48, 'Self-Preservation', '', '', 'Survivor', 'self_preservation.webp'),
       (5, 'Septic Touch', '', '', 'Killer', 'septic_touch.webp'),
       (5, 'Shadowborn', '', '', 'Killer', 'shadowborn.webp'),
       (5, 'Shattered Hope', '', '', 'Killer', 'shattered_hope.webp'),
       (48, 'Slippery Meat', '', '', 'Survivor', 'slippery_meat.webp'),
       (5, 'Sloppy Butcher', '', '', 'Killer', 'sloppy_butcher.webp'),
       (48, 'Small Game', '', '', 'Survivor', 'small_game.webp'),
       (48, 'Smash Hit', '', '', 'Survivor', 'smash_hit.webp'),
       (48, 'Sole Survivor', '', '', 'Survivor', 'sole_survivor.webp'),
       (48, 'Solidarity', '', '', 'Survivor', 'solidarity.webp'),
       (48, 'Soul Guard', '', '', 'Survivor', 'soul_guard.webp'),
       (48, 'Specialist', '', '', 'Survivor', 'specialist.webp'),
       (5, 'Spies From The Shadows', '', '', 'Killer', 'spies_from_the_shadows.webp'),
       (48, 'Spine Chill', '', '', 'Survivor', 'spine_chill.webp'),
       (5, 'Spirit Fury', '', '', 'Killer', 'spirit_fury.webp'),
       (48, 'Sprint Burst', '', '', 'Survivor', 'sprint_burst.webp'),
       (48, 'Stake Out', '', '', 'Survivor', 'stake_out.webp'),
       (5, 'Starstruck', '', '', 'Killer', 'starstruck.webp'),
       (48, 'Streetwise', '', '', 'Survivor', 'streetwise.webp'),
       (48, 'Strength In Shadows', '', '', 'Survivor', 'strength_in_shadows.webp'),
       (5, 'Stridor', '', '', 'Killer', 'stridor.webp'),
       (5, 'Superior Anatomy', '', '', 'Killer', 'superior_anatomy.webp'),
       (5, 'Surge', '', '', 'Killer', 'surge.webp'),
       (5, 'Surveillance', '', '', 'Killer', 'surveillance.webp'),
       (48, 'Teamwork: Collective Stealth', '', '', 'Survivor', 'teamwork_collective_stealth.webp'),
       (48, 'Teamwork: Power Of Two', '', '', 'Survivor', 'teamwork_power_of_two.webp'),
       (48, 'Technician', '', '', 'Survivor', 'technician.webp'),
       (48, 'Tenacity', '', '', 'Survivor', 'tenacity.webp'),
       (5, 'Terminus', '', '', 'Killer', 'terminus.webp'),
       (5, 'Territorial Imperative', '', '', 'Killer', 'territorial_imperative.webp'),
       (5, 'Thanatophobia', '', '', 'Killer', 'thanatophobia.webp'),
       (5, 'The Third Seal', '', '', 'Killer', 'the_third_seal.webp'),
       (48, 'This Is Not Happening', '', '', 'Survivor', 'this_is_not_happening.webp'),
       (5, 'Thrill Of The Hunt', '', '', 'Killer', 'thrill_of_the_hunt.webp'),
       (5, 'Thrilling Tremors', '', '', 'Killer', 'thrilling_tremors.webp'),
       (5, 'Thwack', '', '', 'Killer', 'thwack.webp'),
       (5, 'Tinkerer', '', '', 'Killer', 'tinkerer.webp'),
       (5, 'Trail Of Torment', '', '', 'Killer', 'trail_of_torment.webp'),
       (48, 'Troubleshooter', '', '', 'Survivor', 'troubleshooter.webp'),
       (5, 'Two Can Play', '', '', 'Killer', 'two_can_play.webp'),
       (5, 'Ultimate Weapon', '', '', 'Killer', 'ultimate_weapon.webp'),
       (48, 'Unbreakable', '', '', 'Survivor', 'unbreakable.webp'),
       (5, 'Undying', '', '', 'Killer', 'undying.webp'),
       (5, 'Unnerving Presence', '', '', 'Killer', 'unnerving_presence.webp'),
       (5, 'Unrelenting', '', '', 'Killer', 'unrelenting.webp'),
       (48, 'Up The Ante', '', '', 'Survivor', 'up_the_ante.webp'),
       (48, 'Urban Evasion', '', '', 'Survivor', 'urban_evasion.webp'),
       (48, 'Vigil', '', '', 'Survivor', 'vigil.webp'),
       (48, 'Visionary', '', '', 'Survivor', 'visionary.webp'),
       (48, 'Wake Up', '', '', 'Survivor', 'wake_up.webp'),
       (48, 'Well Make It', '', '', 'Survivor', 'well_make_it.webp'),
       (48, 'Were Gonna Live Forever', '', '', 'Survivor', 'were_gonna_live_forever.webp'),
       (5, 'Whispers', '', '', 'Killer', 'whispers.webp'),
       (48, 'Wicked', '', '', 'Survivor', 'wicked.webp'),
       (48, 'Windows Of Opportunity', '', '', 'Survivor', 'windows_of_opportunity.webp'),
       (48, 'Wiretap', '', '', 'Survivor', 'wiretap.webp'),
       (37, 'Zanshin Tactics', '', '', 'Killer', 'zanshin_tactics.webp');
